{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ required "frontend.name is required" .Values.frontend.name }}
  labels:
    {{- range $key, $value := .Values.frontend.labels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  namespace: {{ required "namespace is required" .Values.namespace }}
spec:
  type: {{ required "frontend.service.type is required" .Values.frontend.service.type }}
  ports:
    - port: {{ required "frontend.service.port is required" .Values.frontend.service.port }}
      targetPort: {{ required "frontend.service.targetPort is required" .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- range $key, $value := .Values.frontend.labels }}
      {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}