{{- range $component, $values := .Values }}
{{- if and (ne $component "namespace") (ne $component "environment") (ne $component "postgresql") (ne $component "networkPolicy") (kindIs "map" $values) (hasKey $values "enabled") }}
{{- if $values.enabled }}
{{- $serviceAccountName := default $values.name (index $values "serviceAccountName") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ required "namespace is required" $.Values.namespace }}
  labels:
    {{- range $key, $value := $values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
automountServiceAccountToken: {{ default false (index $values "automountServiceAccountToken") }}
{{- end }}
{{- end }}
{{- end }}
